### ISSUE TITLE
Why there is no upgrade_lock< std::shared_lock<Mutex> >? Without time?

### ISSUE THREAD

**Issue by tower120** [HowardHinnant/upgrade_mutex#1]
Why `upgrade_lock` have no
```C++
    upgrade_lock(std::shared_lock<mutex_type>&& sl)
```
constructor?

`upgrade_mutex` does not have `unlock_shared_and_lock_upgrade`, also. There is only timed version `try_unlock_shared_and_lock_upgrade_for` / `try_unlock_shared_and_lock_upgrade_until`.

P.S. It seems that boost have these timeless versions...

**Comment by HowardHinnant** [comment]
`upgrade_lock` can not be constructed with a `shared_lock` because there is no `unlock_shared_and_lock_upgrade` as you observed.  And the rationale for that is described in detail here: http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2007/n2406.html#upgrade_mutex_rationale

In a nutshell, upgrade ownership is a form of unique ownership itself.  Though it can share with threads with shared ownership, it can not share with other threads that have upgrade ownership.  The rationale for that is if you have two threads with upgrade ownership and they both ask for unique ownership at the same time, the program deadlocks.

Thus since only one thread can have upgrade ownership at one time, if two threads with shared ownership both ask for upgrade ownership at the same time, they also deadlock.  You can do try and timed attempts at this transition, allowing one of the threads with shared ownership to transition, and one to fail, thus avoiding deadlock.

The boost version of this design was copied from mine, and they added this dangerous API over my objections.

**Comment by tower120** [comment]
I read your rationale http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2007/n2406.html#upgrade_mutex_rationale > Interesting thing. Generally speaking, only unique_lock -> shared_lock can be done reliably.


> You can do try and timed attempts at this transition, allowing one of the threads with shared ownership to transition, and one to fail, thus avoiding deadlock.

So.... In the following pseudo-code:
```C++
  upgrade_mutex lock;
  void add(){
     std::unique_lock<upgrade_mutex> l(lock);

  }

  void test(){
      std::shared_lock<upgrade_mutex> l(lock);
      // A. do something...
      while( !lock.try_unlock_shared_and_lock_upgrade_for(1ms) ){
          std::this_thread::yield();
      }
     // B. 
     lock.unlock();
  }
```

between A and B, can add() be called?
I mean, is it guaranteed that unlock_shared_and_lock_upgrade "queue" will be called first?

**Comment by HowardHinnant** [comment]
I find it easiest to understand using a diagram of the three types of locked states.  This triangle should really include the unlocked state as well, but it becomes visually messier when you try to do so:
````
unique
  |   \
  |    \
  |    upgrade
  |    /
  |   /
shared
````

Going down the triangle, all conversions are non-blocking:  E.g. unique -> shared, and unique -> upgrade, and upgrade -> shared.

Going up the triangle you can only do timed and try conversions _except_ for upgrade -> unique.  This conversion is guaranteed to succeed, but is blocking.  It blocks until the one thread that has unique ownership transitions to the unlocked state, or until all threads that have shared ownership transition to unlocked.

In your example it is guaranteed that another thread can not unique-lock `lock` until `test` reaches B.  It is not guaranteed that `test` will ever reach B.  That `while` could loop forever, resulting in effective deadlock.  <del>For example if two threads execute `test` simultaneously, they will deadlock against each other.</del>

Bad example.  Let me try again:  Thread A holds shared ownership of `lock`.  Thread B holds upgrade ownership of `lock` and attempts to transition to unique ownership, but blocks until A unlocks.  Now thread C executes `test`.  This results in deadlock.  Even after Thread A unlocks, B is waiting on C to unlock and C is waiting on B to unlock.

Sigh, the above is still not exactly correct, but it is close.  C won't get the shared ownership if B has already begun the request for unique ownership.  But if C gets the shared ownership _then_ B blocks on the transition: bang you're dead.  I guess we don't even need A.  We just need B to have upgrade ownership, then have C execute `test`, then have B block on upgrade->unique.

It is because of this difficult-to-analyze topic that this library tries to detect as many of these problems as it can using the type system (at compile time).  A blocking transition from shared to upgrade can deadlock.  This is true whether there is a `unlock_shared_and_lock_upgrade`, or whether you build a blocking transition out of a loop and `try_unlock_shared_and_lock_upgrade_for`.

If you loop forever using a `try_` transition, you are risking deadlock.  The `try_` transitions should be viewed as "opportunistic", but not as a way to guarantee a transition.

**Comment by tower120** [comment]
> The try_ transitions should be viewed as "opportunistic", but not as a way to guarantee a transition.

Is this "opportunistic" approach used somewhere (for your knowledge)? I would like to see algorithm, that exploit this feature. I mean, example with `try_unlock_shared_and_lock_upgrade_for` that actually do something.

P.S. Sorry, for this maybe stupid question, but... I see how unique_ptr -> shared_ptr `try_` transition can help (in many cases if it fail to transition - you'll just have performance penalty); but if you need vice versa transition - then you likely going to mutate something with `unique_ptr` lock (and how to do this on conditional terms of `try_`?).

**Comment by HowardHinnant** [comment]
A unique ownership to shared never fails, or even blocks.  It always succeeds immediately.  There's not even a try/timed variant of this transition because there is no need for one.

I don't have code handy that uses `try_unlock_shared_and_lock_upgrade_for`.  But an example might look like this:

Say you've done a considerable amount of work under shared ownership, and you unexpectedly see that you _might_ need unique ownership.  To prepare for that you could try to transition to upgrade ownership.  If successful, you can transition from upgrade to unique without fail.  If unsuccessful, you could relinquish (unlock) your shared ownership, and block on `lock_upgrade`.  Once obtained, you might discover that the work you did while you held the shared ownership has been undone by another thread, and you therefore might need to redo that work.  Or you might discover that your need/motivation for the upgrade ownership was work that has now already been done by another thread, and so you can just drop all ownership.

In the above scenario, failing the `try_unlock_shared_and_lock_upgrade_for` is not a correctness issue, but a performance issue.  The code is faster if the transition succeeds, but a slow path exists that is still correct.

Please understand that scenarios like these are relatively rare and specialized.  95% of the time, you should be using `mutex`.  It is simple and fast.  Maybe another 4% of the time `shared_mutex` might offer some advantages (read/write scenario with no need to atomically transition from read to write mode).  The upgrade functionality exists for that remaining 1% of the time that is relatively complicated, and can offer a potential performance boost over the vanilla read/write pattern.  It is mainly because of this relatively rare use that the committee was never motivated to standardize it.

**Comment by tower120** [comment]
I see, thank you for your explanation.
